# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

var_for_docker_image: &docker_image circleci/python:2.7.17-browsers

anchor_for_job_defaults: &job_defaults
  working_directory: /home/circleci/testing
  docker:
    - image: *docker_image
jobs:
  setup_and_typescript_tests:
    <<: *job_defaults
    steps:
      - checkout
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - setup_and_typescript_test
